#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.7.3
# from Racc grammar file "parser.y".
#

###### racc/parser.rb begin
unless $".find {|p| p.end_with?('/racc/parser.rb')}
$".push "#{__dir__}/racc/parser.rb"
self.class.module_eval(<<'...end racc/parser.rb/module_eval...', 'racc/parser.rb', 1)
#--
# Copyright (c) 1999-2006 Minero Aoki
#
# This program is free software.
# You can distribute/modify this program under the same terms of ruby.
#
# As a special exception, when this code is copied by Racc
# into a Racc output file, you may use that output file
# without restriction.
#++

unless $".find {|p| p.end_with?('/racc/info.rb')}
$".push "#{__dir__}/racc/info.rb"

module Racc
  VERSION   = '1.7.3'
  Version = VERSION
  Copyright = 'Copyright (c) 1999-2006 Minero Aoki'
end

end


unless defined?(NotImplementedError)
  NotImplementedError = NotImplementError # :nodoc:
end

module Racc
  class ParseError < StandardError; end
end
unless defined?(::ParseError)
  ParseError = Racc::ParseError # :nodoc:
end

# Racc is a LALR(1) parser generator.
# It is written in Ruby itself, and generates Ruby programs.
#
# == Command-line Reference
#
#     racc [-o<var>filename</var>] [--output-file=<var>filename</var>]
#          [-e<var>rubypath</var>] [--executable=<var>rubypath</var>]
#          [-v] [--verbose]
#          [-O<var>filename</var>] [--log-file=<var>filename</var>]
#          [-g] [--debug]
#          [-E] [--embedded]
#          [-l] [--no-line-convert]
#          [-c] [--line-convert-all]
#          [-a] [--no-omit-actions]
#          [-C] [--check-only]
#          [-S] [--output-status]
#          [--version] [--copyright] [--help] <var>grammarfile</var>
#
# [+grammarfile+]
#   Racc grammar file. Any extension is permitted.
# [-o+outfile+, --output-file=+outfile+]
#   A filename for output. default is <+filename+>.tab.rb
# [-O+filename+, --log-file=+filename+]
#   Place logging output in file +filename+.
#   Default log file name is <+filename+>.output.
# [-e+rubypath+, --executable=+rubypath+]
#   output executable file(mode 755). where +path+ is the Ruby interpreter.
# [-v, --verbose]
#   verbose mode. create +filename+.output file, like yacc's y.output file.
# [-g, --debug]
#   add debug code to parser class. To display debugging information,
#   use this '-g' option and set @yydebug true in parser class.
# [-E, --embedded]
#   Output parser which doesn't need runtime files (racc/parser.rb).
# [-F, --frozen]
#   Output parser which declares frozen_string_literals: true
# [-C, --check-only]
#   Check syntax of racc grammar file and quit.
# [-S, --output-status]
#   Print messages time to time while compiling.
# [-l, --no-line-convert]
#   turns off line number converting.
# [-c, --line-convert-all]
#   Convert line number of actions, inner, header and footer.
# [-a, --no-omit-actions]
#   Call all actions, even if an action is empty.
# [--version]
#   print Racc version and quit.
# [--copyright]
#   Print copyright and quit.
# [--help]
#   Print usage and quit.
#
# == Generating Parser Using Racc
#
# To compile Racc grammar file, simply type:
#
#   $ racc parse.y
#
# This creates Ruby script file "parse.tab.y". The -o option can change the output filename.
#
# == Writing A Racc Grammar File
#
# If you want your own parser, you have to write a grammar file.
# A grammar file contains the name of your parser class, grammar for the parser,
# user code, and anything else.
# When writing a grammar file, yacc's knowledge is helpful.
# If you have not used yacc before, Racc is not too difficult.
#
# Here's an example Racc grammar file.
#
#   class Calcparser
#   rule
#     target: exp { print val[0] }
#
#     exp: exp '+' exp
#        | exp '*' exp
#        | '(' exp ')'
#        | NUMBER
#   end
#
# Racc grammar files resemble yacc files.
# But (of course), this is Ruby code.
# yacc's $$ is the 'result', $0, $1... is
# an array called 'val', and $-1, $-2... is an array called '_values'.
#
# See the {Grammar File Reference}[rdoc-ref:lib/racc/rdoc/grammar.en.rdoc] for
# more information on grammar files.
#
# == Parser
#
# Then you must prepare the parse entry method. There are two types of
# parse methods in Racc, Racc::Parser#do_parse and Racc::Parser#yyparse
#
# Racc::Parser#do_parse is simple.
#
# It's yyparse() of yacc, and Racc::Parser#next_token is yylex().
# This method must returns an array like [TOKENSYMBOL, ITS_VALUE].
# EOF is [false, false].
# (TOKENSYMBOL is a Ruby symbol (taken from String#intern) by default.
# If you want to change this, see the grammar reference.
#
# Racc::Parser#yyparse is little complicated, but useful.
# It does not use Racc::Parser#next_token, instead it gets tokens from any iterator.
#
# For example, <code>yyparse(obj, :scan)</code> causes
# calling +obj#scan+, and you can return tokens by yielding them from +obj#scan+.
#
# == Debugging
#
# When debugging, "-v" or/and the "-g" option is helpful.
#
# "-v" creates verbose log file (.output).
# "-g" creates a "Verbose Parser".
# Verbose Parser prints the internal status when parsing.
# But it's _not_ automatic.
# You must use -g option and set +@yydebug+ to +true+ in order to get output.
# -g option only creates the verbose parser.
#
# === Racc reported syntax error.
#
# Isn't there too many "end"?
# grammar of racc file is changed in v0.10.
#
# Racc does not use '%' mark, while yacc uses huge number of '%' marks..
#
# === Racc reported "XXXX conflicts".
#
# Try "racc -v xxxx.y".
# It causes producing racc's internal log file, xxxx.output.
#
# === Generated parsers does not work correctly
#
# Try "racc -g xxxx.y".
# This command let racc generate "debugging parser".
# Then set @yydebug=true in your parser.
# It produces a working log of your parser.
#
# == Re-distributing Racc runtime
#
# A parser, which is created by Racc, requires the Racc runtime module;
# racc/parser.rb.
#
# Ruby 1.8.x comes with Racc runtime module,
# you need NOT distribute Racc runtime files.
#
# If you want to include the Racc runtime module with your parser.
# This can be done by using '-E' option:
#
#   $ racc -E -omyparser.rb myparser.y
#
# This command creates myparser.rb which `includes' Racc runtime.
# Only you must do is to distribute your parser file (myparser.rb).
#
# Note: parser.rb is ruby license, but your parser is not.
# Your own parser is completely yours.
module Racc

  unless defined?(Racc_No_Extensions)
    Racc_No_Extensions = false # :nodoc:
  end

  class Parser

    Racc_Runtime_Version = ::Racc::VERSION
    Racc_Runtime_Core_Version_R = ::Racc::VERSION

    begin
      if Object.const_defined?(:RUBY_ENGINE) and RUBY_ENGINE == 'jruby'
        require 'jruby'
        require 'racc/cparse-jruby.jar'
        com.headius.racc.Cparse.new.load(JRuby.runtime, false)
      else
        require 'racc/cparse'
      end

      unless new.respond_to?(:_racc_do_parse_c, true)
        raise LoadError, 'old cparse.so'
      end
      if Racc_No_Extensions
        raise LoadError, 'selecting ruby version of racc runtime core'
      end

      Racc_Main_Parsing_Routine    = :_racc_do_parse_c # :nodoc:
      Racc_YY_Parse_Method         = :_racc_yyparse_c # :nodoc:
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_C # :nodoc:
      Racc_Runtime_Type            = 'c' # :nodoc:
    rescue LoadError
      Racc_Main_Parsing_Routine    = :_racc_do_parse_rb
      Racc_YY_Parse_Method         = :_racc_yyparse_rb
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_R
      Racc_Runtime_Type            = 'ruby'
    end

    def Parser.racc_runtime_type # :nodoc:
      Racc_Runtime_Type
    end

    def _racc_setup
      @yydebug = false unless self.class::Racc_debug_parser
      @yydebug = false unless defined?(@yydebug)
      if @yydebug
        @racc_debug_out = $stderr unless defined?(@racc_debug_out)
        @racc_debug_out ||= $stderr
      end
      arg = self.class::Racc_arg
      arg[13] = true if arg.size < 14
      arg
    end

    def _racc_init_sysvars
      @racc_state  = [0]
      @racc_tstack = []
      @racc_vstack = []

      @racc_t = nil
      @racc_val = nil

      @racc_read_next = true

      @racc_user_yyerror = false
      @racc_error_status = 0
    end

    # The entry point of the parser. This method is used with #next_token.
    # If Racc wants to get token (and its value), calls next_token.
    #
    # Example:
    #     def parse
    #       @q = [[1,1],
    #             [2,2],
    #             [3,3],
    #             [false, '$']]
    #       do_parse
    #     end
    #
    #     def next_token
    #       @q.shift
    #     end
    class_eval <<~RUBY, __FILE__, __LINE__ + 1
    def do_parse
      #{Racc_Main_Parsing_Routine}(_racc_setup(), false)
    end
    RUBY

    # The method to fetch next token.
    # If you use #do_parse method, you must implement #next_token.
    #
    # The format of return value is [TOKEN_SYMBOL, VALUE].
    # +token-symbol+ is represented by Ruby's symbol by default, e.g. :IDENT
    # for 'IDENT'.  ";" (String) for ';'.
    #
    # The final symbol (End of file) must be false.
    def next_token
      raise NotImplementedError, "#{self.class}\#next_token is not defined"
    end

    def _racc_do_parse_rb(arg, in_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars
      tok = act = i = nil

      catch(:racc_end_parse) {
        while true
          if i = action_pointer[@racc_state[-1]]
            if @racc_read_next
              if @racc_t != 0   # not EOF
                tok, @racc_val = next_token()
                unless tok      # EOF
                  @racc_t = 0
                else
                  @racc_t = (token_table[tok] or 1)   # error token
                end
                racc_read_token(@racc_t, tok, @racc_val) if @yydebug
                @racc_read_next = false
              end
            end
            i += @racc_t
            unless i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
          else
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end
        end
      }
    end

    # Another entry point for the parser.
    # If you use this method, you must implement RECEIVER#METHOD_ID method.
    #
    # RECEIVER#METHOD_ID is a method to get next token.
    # It must 'yield' the token, which format is [TOKEN-SYMBOL, VALUE].
    class_eval <<~RUBY, __FILE__, __LINE__ + 1
    def yyparse(recv, mid)
      #{Racc_YY_Parse_Method}(recv, mid, _racc_setup(), false)
    end
    RUBY

    def _racc_yyparse_rb(recv, mid, arg, c_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars

      catch(:racc_end_parse) {
        until i = action_pointer[@racc_state[-1]]
          while act = _racc_evalact(action_default[@racc_state[-1]], arg)
            ;
          end
        end
        recv.__send__(mid) do |tok, val|
          unless tok
            @racc_t = 0
          else
            @racc_t = (token_table[tok] or 1)   # error token
          end
          @racc_val = val
          @racc_read_next = false

          i += @racc_t
          unless i >= 0 and
                 act = action_table[i] and
                 action_check[i] == @racc_state[-1]
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end

          while !(i = action_pointer[@racc_state[-1]]) ||
                ! @racc_read_next ||
                @racc_t == 0  # $
            unless i and i += @racc_t and
                   i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
            while act = _racc_evalact(act, arg)
              ;
            end
          end
        end
      }
    end

    ###
    ### common
    ###

    def _racc_evalact(act, arg)
      action_table, action_check, _, action_pointer,
      _,            _,            _, _,
      _,            _,            _, shift_n,
      reduce_n,     * = arg
      nerr = 0   # tmp

      if act > 0 and act < shift_n
        #
        # shift
        #
        if @racc_error_status > 0
          @racc_error_status -= 1 unless @racc_t <= 1 # error token or EOF
        end
        @racc_vstack.push @racc_val
        @racc_state.push act
        @racc_read_next = true
        if @yydebug
          @racc_tstack.push @racc_t
          racc_shift @racc_t, @racc_tstack, @racc_vstack
        end

      elsif act < 0 and act > -reduce_n
        #
        # reduce
        #
        code = catch(:racc_jump) {
          @racc_state.push _racc_do_reduce(arg, act)
          false
        }
        if code
          case code
          when 1 # yyerror
            @racc_user_yyerror = true   # user_yyerror
            return -reduce_n
          when 2 # yyaccept
            return shift_n
          else
            raise '[Racc Bug] unknown jump code'
          end
        end

      elsif act == shift_n
        #
        # accept
        #
        racc_accept if @yydebug
        throw :racc_end_parse, @racc_vstack[0]

      elsif act == -reduce_n
        #
        # error
        #
        case @racc_error_status
        when 0
          unless arg[21]    # user_yyerror
            nerr += 1
            on_error @racc_t, @racc_val, @racc_vstack
          end
        when 3
          if @racc_t == 0   # is $
            # We're at EOF, and another error occurred immediately after
            # attempting auto-recovery
            throw :racc_end_parse, nil
          end
          @racc_read_next = true
        end
        @racc_user_yyerror = false
        @racc_error_status = 3
        while true
          if i = action_pointer[@racc_state[-1]]
            i += 1   # error token
            if  i >= 0 and
                (act = action_table[i]) and
                action_check[i] == @racc_state[-1]
              break
            end
          end
          throw :racc_end_parse, nil if @racc_state.size <= 1
          @racc_state.pop
          @racc_vstack.pop
          if @yydebug
            @racc_tstack.pop
            racc_e_pop @racc_state, @racc_tstack, @racc_vstack
          end
        end
        return act

      else
        raise "[Racc Bug] unknown action #{act.inspect}"
      end

      racc_next_state(@racc_state[-1], @racc_state) if @yydebug

      nil
    end

    def _racc_do_reduce(arg, act)
      _,          _,            _,            _,
      goto_table, goto_check,   goto_default, goto_pointer,
      nt_base,    reduce_table, _,            _,
      _,          use_result,   * = arg

      state = @racc_state
      vstack = @racc_vstack
      tstack = @racc_tstack

      i = act * -3
      len       = reduce_table[i]
      reduce_to = reduce_table[i+1]
      method_id = reduce_table[i+2]
      void_array = []

      tmp_t = tstack[-len, len] if @yydebug
      tmp_v = vstack[-len, len]
      tstack[-len, len] = void_array if @yydebug
      vstack[-len, len] = void_array
      state[-len, len]  = void_array

      # tstack must be updated AFTER method call
      if use_result
        vstack.push __send__(method_id, tmp_v, vstack, tmp_v[0])
      else
        vstack.push __send__(method_id, tmp_v, vstack)
      end
      tstack.push reduce_to

      racc_reduce(tmp_t, reduce_to, tstack, vstack) if @yydebug

      k1 = reduce_to - nt_base
      if i = goto_pointer[k1]
        i += state[-1]
        if i >= 0 and (curstate = goto_table[i]) and goto_check[i] == k1
          return curstate
        end
      end
      goto_default[k1]
    end

    # This method is called when a parse error is found.
    #
    # ERROR_TOKEN_ID is an internal ID of token which caused error.
    # You can get string representation of this ID by calling
    # #token_to_str.
    #
    # ERROR_VALUE is a value of error token.
    #
    # value_stack is a stack of symbol values.
    # DO NOT MODIFY this object.
    #
    # This method raises ParseError by default.
    #
    # If this method returns, parsers enter "error recovering mode".
    def on_error(t, val, vstack)
      raise ParseError, sprintf("parse error on value %s (%s)",
                                val.inspect, token_to_str(t) || '?')
    end

    # Enter error recovering mode.
    # This method does not call #on_error.
    def yyerror
      throw :racc_jump, 1
    end

    # Exit parser.
    # Return value is +Symbol_Value_Stack[0]+.
    def yyaccept
      throw :racc_jump, 2
    end

    # Leave error recovering mode.
    def yyerrok
      @racc_error_status = 0
    end

    # For debugging output
    def racc_read_token(t, tok, val)
      @racc_debug_out.print 'read    '
      @racc_debug_out.print tok.inspect, '(', racc_token2str(t), ') '
      @racc_debug_out.puts val.inspect
      @racc_debug_out.puts
    end

    def racc_shift(tok, tstack, vstack)
      @racc_debug_out.puts "shift   #{racc_token2str tok}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_reduce(toks, sim, tstack, vstack)
      out = @racc_debug_out
      out.print 'reduce '
      if toks.empty?
        out.print ' <none>'
      else
        toks.each {|t| out.print ' ', racc_token2str(t) }
      end
      out.puts " --> #{racc_token2str(sim)}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_accept
      @racc_debug_out.puts 'accept'
      @racc_debug_out.puts
    end

    def racc_e_pop(state, tstack, vstack)
      @racc_debug_out.puts 'error recovering mode: pop token'
      racc_print_states state
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_next_state(curstate, state)
      @racc_debug_out.puts  "goto    #{curstate}"
      racc_print_states state
      @racc_debug_out.puts
    end

    def racc_print_stacks(t, v)
      out = @racc_debug_out
      out.print '        ['
      t.each_index do |i|
        out.print ' (', racc_token2str(t[i]), ' ', v[i].inspect, ')'
      end
      out.puts ' ]'
    end

    def racc_print_states(s)
      out = @racc_debug_out
      out.print '        ['
      s.each {|st| out.print ' ', st }
      out.puts ' ]'
    end

    def racc_token2str(tok)
      self.class::Racc_token_to_s_table[tok] or
          raise "[Racc Bug] can't convert token #{tok} to string"
    end

    # Convert internal ID of token symbol to the string.
    def token_to_str(t)
      self.class::Racc_token_to_s_table[t]
    end

  end

end

...end racc/parser.rb/module_eval...
end
###### racc/parser.rb end
module Lrama
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 520)

include Lrama::Report::Duration

def initialize(text, path, debug = false)
  @grammar_file = Lrama::Lexer::GrammarFile.new(path, text)
  @yydebug = debug
  @rule_counter = Lrama::Grammar::Counter.new(0)
  @midrule_action_counter = Lrama::Grammar::Counter.new(1)
end

def parse
  report_duration(:parse) do
    @lexer = Lrama::Lexer.new(@grammar_file)
    @grammar = Lrama::Grammar.new(@rule_counter)
    @precedence_number = 0
    reset_precs
    do_parse
    @grammar.prepare
    @grammar.validate!
    @grammar
  end
end

def next_token
  @lexer.next_token
end

def on_error(error_token_id, error_value, value_stack)
  if error_value.is_a?(Lrama::Lexer::Token)
    location = error_value.location
    value = "'#{error_value.s_value}'"
  else
    location = @lexer.location
    value = error_value.inspect
  end

  error_message = "parse error on value #{value} (#{token_to_str(error_token_id) || '?'})"

  raise_parse_error(error_message, location)
end

def on_action_error(error_message, error_value)
  if error_value.is_a?(Lrama::Lexer::Token)
    location = error_value.location
  else
    location = @lexer.location
  end

  raise_parse_error(error_message, location)
end

private

def reset_precs
  @prec_seen = false
  @code_after_prec = false
end

def begin_c_declaration(end_symbol)
  @lexer.status = :c_declaration
  @lexer.end_symbol = end_symbol
end

def end_c_declaration
  @lexer.status = :initial
  @lexer.end_symbol = nil
end

def raise_parse_error(error_message, location)
  raise ParseError, location.generate_error_message(error_message)
end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    91,    47,    92,   154,     3,    73,    47,    47,   154,   198,
    73,    73,    47,   153,   198,     8,    73,   156,   209,    47,
    37,    46,   156,   199,    64,   173,   174,   175,   199,    44,
    50,    47,   152,    46,    43,    73,    69,    47,    47,    46,
    46,   157,    76,    76,    93,    50,   157,   200,   173,   174,
   175,    89,   200,    21,    23,    24,    25,    26,    27,    28,
    29,    30,    31,    32,    33,    34,    43,    47,    47,    46,
    46,    86,    76,    76,    47,     6,    46,     7,    73,   183,
    47,    47,    46,    46,    73,    21,    23,    24,    25,    26,
    27,    28,    29,    30,    31,    32,    33,    34,     9,    47,
    50,    46,    13,    14,    15,    16,    17,    18,    53,    54,
    19,    20,    21,    23,    24,    25,    26,    27,    28,    29,
    30,    31,    32,    33,    34,    35,    47,    47,    46,    46,
    73,   183,    47,    47,    46,    46,    73,   183,    47,    47,
    46,    46,    73,   183,    47,    47,    46,    46,    73,   183,
    47,    47,    46,    46,    73,   183,    47,    47,    46,    46,
    73,    73,    47,    47,    46,    46,    73,    73,    47,    47,
    46,   189,    73,    73,    47,    47,    46,   189,    73,    73,
    47,    47,    46,   189,    73,    73,    47,    47,    46,    46,
    47,    47,    46,    46,   150,   202,   151,   203,   173,   174,
   175,   218,   220,   203,   203,    55,    56,    57,    58,    59,
    60,    61,    82,    83,    87,    89,    94,    94,    94,    96,
   103,   107,   108,   111,   111,   111,   111,   114,   117,   118,
   120,   122,   123,   124,   125,   126,   127,   130,   134,   135,
   136,   139,   140,   141,   143,   159,   161,   162,   163,   164,
   165,   166,   167,   168,   139,   170,   178,   179,   188,   193,
   194,   196,   201,   188,    89,   193,   215,   217,    89,   222,
    89 ]

racc_action_check = [
    45,   138,    45,   138,     1,   138,   169,   187,   169,   187,
   169,   187,   206,   137,   206,     3,   206,   138,   198,    29,
     7,    29,   169,   187,    29,   198,   198,   198,   206,    13,
    15,    30,   137,    30,     9,    30,    30,    31,    32,    31,
    32,   138,    31,    32,    45,    16,   169,   187,   155,   155,
   155,   155,   206,     9,     9,     9,     9,     9,     9,     9,
     9,     9,     9,     9,     9,     9,    38,    33,    34,    33,
    34,    38,    33,    34,   163,     2,   163,     2,   163,   163,
    68,    14,    68,    14,    68,    38,    38,    38,    38,    38,
    38,    38,    38,    38,    38,    38,    38,    38,     4,    63,
    17,    63,     4,     4,     4,     4,     4,     4,    18,    19,
     4,     4,     4,     4,     4,     4,     4,     4,     4,     4,
     4,     4,     4,     4,     4,     4,   164,    64,   164,    64,
   164,   164,   165,    75,   165,    75,   165,   165,   180,    76,
   180,    76,   180,   180,   184,   103,   184,   103,   184,   184,
   185,   105,   185,   105,   185,   185,    69,   108,    69,   108,
    69,   108,   110,   131,   110,   131,   110,   131,   157,   170,
   157,   170,   157,   170,   200,   201,   200,   201,   200,   201,
   203,   209,   203,   209,   203,   209,   111,   113,   111,   113,
   128,   132,   128,   132,   133,   190,   133,   190,   191,   191,
   191,   212,   216,   212,   216,    21,    23,    24,    25,    26,
    27,    28,    35,    36,    41,    42,    49,    51,    52,    53,
    62,    66,    67,    74,    79,    80,    81,    82,    88,    89,
    95,    97,    98,    99,   100,   101,   102,   106,   114,   115,
   116,   117,   118,   119,   121,   142,   144,   145,   146,   147,
   148,   149,   150,   151,   152,   154,   158,   160,   167,   172,
   176,   186,   189,   196,   197,   202,   205,   210,   215,   221,
   222 ]

racc_action_pointer = [
   nil,     4,    65,    15,    89,   nil,   nil,    13,   nil,    30,
   nil,   nil,   nil,    23,    78,    11,    26,    81,   103,    90,
   nil,   186,   nil,   187,   188,   189,   190,   205,   206,    16,
    28,    34,    35,    64,    65,   207,   211,   nil,    62,   nil,
   nil,   192,   168,   nil,   nil,    -5,   nil,   nil,   nil,   197,
   nil,   198,   199,   200,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   212,    96,   124,   nil,   215,   214,    77,   153,
   nil,   nil,   nil,   nil,   215,   130,   136,   nil,   nil,   216,
   217,   218,   190,   nil,   nil,   nil,   nil,   nil,   189,   224,
   nil,   nil,   nil,   nil,   nil,   228,   nil,   229,   230,   231,
   232,   233,   234,   142,   nil,   148,   230,   nil,   154,   nil,
   159,   183,   nil,   184,   233,   228,   238,   199,   194,   241,
   nil,   242,   nil,   nil,   nil,   nil,   nil,   nil,   187,   nil,
   nil,   160,   188,   156,   nil,   nil,   nil,    -9,    -2,   nil,
   nil,   nil,   225,   nil,   226,   227,   228,   229,   230,   231,
   213,   248,   212,   nil,   218,     4,   nil,   165,   236,   nil,
   237,   nil,   nil,    71,   123,   129,   nil,   216,   nil,     3,
   166,   nil,   251,   nil,   nil,   nil,   258,   nil,   nil,   nil,
   135,   nil,   nil,   nil,   141,   147,   220,     4,   nil,   225,
   157,   154,   nil,   nil,   nil,   nil,   221,   217,   -19,   nil,
   171,   172,   257,   177,   nil,   246,     9,   nil,   nil,   178,
   265,   nil,   163,   nil,   nil,   221,   164,   nil,   nil,   nil,
   nil,   249,   223,   nil ]

racc_action_default = [
    -2,  -135,    -8,  -135,  -135,    -3,    -4,  -135,   224,  -135,
    -9,   -10,   -11,  -135,  -135,  -135,  -135,  -135,  -135,  -135,
   -23,  -135,   -27,  -135,  -135,  -135,  -135,  -135,  -135,  -135,
  -135,  -135,  -135,  -135,  -135,  -135,  -135,    -7,  -120,   -93,
   -95,  -135,  -117,  -119,   -12,  -124,   -91,   -92,  -123,   -14,
   -82,   -15,   -16,  -135,   -20,   -24,   -28,   -31,   -34,   -37,
   -40,   -41,   -42,   -48,  -135,   -51,   -68,   -43,   -72,  -135,
   -75,   -77,   -78,  -132,   -44,   -85,  -135,   -88,   -90,   -45,
   -46,   -47,  -135,    -5,    -1,   -94,  -121,   -96,  -135,  -135,
   -13,  -125,  -126,  -127,   -79,  -135,   -17,  -135,  -135,  -135,
  -135,  -135,  -135,  -135,   -52,   -49,   -70,   -69,  -135,   -76,
   -73,  -135,   -89,   -86,  -135,  -135,  -135,  -101,  -135,  -135,
   -83,  -135,   -21,   -25,   -29,   -32,   -35,   -38,   -50,   -53,
   -71,   -74,   -87,  -135,   -55,    -6,  -122,   -97,   -98,  -102,
  -118,   -80,  -135,   -18,  -135,  -135,  -135,  -135,  -135,  -135,
  -135,  -135,  -101,  -100,   -91,  -117,  -106,  -135,  -135,   -84,
  -135,   -22,   -26,  -135,  -135,  -135,   -39,   -59,   -56,   -99,
  -135,  -103,  -133,  -110,  -111,  -112,  -135,  -109,   -81,   -19,
   -30,  -128,  -130,  -131,   -33,   -36,   -54,   -57,   -60,   -91,
  -135,  -113,  -104,  -134,  -107,  -129,   -59,  -117,   -91,   -64,
  -135,  -135,  -133,  -135,  -115,  -135,   -58,   -61,   -62,  -135,
  -135,   -67,  -135,  -105,  -114,  -117,  -135,   -65,  -116,  -108,
   -63,  -135,  -117,   -66 ]

racc_goto_table = [
    88,    48,    68,    63,   104,   113,    70,   138,   187,   112,
    39,     1,   172,   192,     2,     4,    66,    38,    78,    78,
    78,    78,   190,   195,    49,    51,    52,   195,   195,    74,
    79,    80,    81,   180,   184,   185,    84,   206,   105,    85,
   132,   110,   169,   213,   109,    70,   104,   112,   204,     5,
    66,    66,    36,   212,   115,   208,    10,    11,    12,    45,
    90,   216,    78,    78,   121,   160,   112,    97,   144,   104,
    98,   145,    99,   146,   100,   147,   101,   128,   148,   102,
   131,   149,    62,    67,    70,   106,   109,   129,   133,   186,
    66,   210,    66,   221,   119,   158,    95,   142,    78,   137,
    78,   176,   205,   116,   nil,   nil,   nil,   109,   nil,   nil,
   nil,   nil,   nil,   171,   155,    66,   nil,   nil,   nil,    78,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   177,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   155,   191,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   207,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   197,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   219,   nil,   nil,   211,   191,   nil,   214,
   223,   nil,   197,   nil,   nil,   191 ]

racc_goto_check = [
    43,    36,    48,    34,    35,    54,    42,    60,    41,    55,
    56,     1,    44,    61,     2,     3,    36,     4,    36,    36,
    36,    36,    45,    65,    14,    14,    14,    65,    65,    33,
    33,    33,    33,    20,    20,    20,     5,    41,    34,    56,
    54,    48,    60,    61,    42,    42,    35,    55,    44,     6,
    36,    36,     7,    45,     8,    44,     9,    10,    11,    12,
    13,    45,    36,    36,    15,    16,    55,    17,    18,    35,
    21,    22,    23,    24,    25,    26,    27,    34,    28,    29,
    48,    30,    31,    32,    42,    37,    42,    38,    39,    40,
    36,    46,    36,    47,    50,    51,    52,    53,    36,    59,
    36,    62,    63,    64,   nil,   nil,   nil,    42,   nil,   nil,
   nil,   nil,   nil,    43,    42,    36,   nil,   nil,   nil,    36,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    42,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    42,    42,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    43,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    42,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    43,   nil,   nil,    42,    42,   nil,    42,
    43,   nil,    42,   nil,   nil,    42 ]

racc_goto_pointer = [
   nil,    11,    14,    13,     8,    -2,    47,    46,   -29,    52,
    53,    54,    45,    15,     9,   -32,   -78,    13,   -54,   nil,
  -130,    15,   -52,    16,   -51,    17,   -50,    18,   -48,    20,
   -46,    53,    53,    -2,   -26,   -59,   -13,    19,   -19,   -26,
   -78,  -159,   -24,   -42,  -143,  -148,  -108,  -124,   -28,   nil,
     0,   -46,    46,   -23,   -71,   -66,     1,   nil,   nil,   -18,
  -110,  -159,   -55,   -92,    17,  -157 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    41,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    22,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    65,    71,   nil,   nil,   nil,
   nil,   nil,   182,   nil,   nil,   nil,   nil,   nil,   nil,    72,
   nil,   nil,   nil,   nil,    75,    77,   nil,    40,    42,   nil,
   nil,   nil,   nil,   nil,   nil,   181 ]

racc_reduce_table = [
  0, 0, :racc_error,
  5, 51, :_reduce_none,
  0, 52, :_reduce_none,
  2, 52, :_reduce_none,
  0, 57, :_reduce_4,
  0, 58, :_reduce_5,
  5, 56, :_reduce_6,
  2, 56, :_reduce_none,
  0, 53, :_reduce_8,
  2, 53, :_reduce_none,
  1, 59, :_reduce_none,
  1, 59, :_reduce_none,
  2, 59, :_reduce_12,
  3, 59, :_reduce_none,
  2, 59, :_reduce_none,
  2, 59, :_reduce_15,
  2, 59, :_reduce_16,
  0, 65, :_reduce_17,
  0, 66, :_reduce_18,
  7, 59, :_reduce_19,
  0, 67, :_reduce_20,
  0, 68, :_reduce_21,
  6, 59, :_reduce_22,
  1, 59, :_reduce_none,
  0, 71, :_reduce_24,
  0, 72, :_reduce_25,
  6, 60, :_reduce_26,
  1, 60, :_reduce_none,
  0, 73, :_reduce_28,
  0, 74, :_reduce_29,
  7, 60, :_reduce_none,
  0, 75, :_reduce_31,
  0, 76, :_reduce_32,
  7, 60, :_reduce_33,
  0, 77, :_reduce_34,
  0, 78, :_reduce_35,
  7, 60, :_reduce_36,
  0, 79, :_reduce_37,
  0, 80, :_reduce_38,
  6, 60, :_reduce_39,
  2, 60, :_reduce_40,
  2, 60, :_reduce_41,
  2, 69, :_reduce_none,
  2, 69, :_reduce_43,
  2, 69, :_reduce_44,
  2, 69, :_reduce_45,
  2, 69, :_reduce_46,
  2, 69, :_reduce_47,
  1, 81, :_reduce_48,
  2, 81, :_reduce_49,
  3, 81, :_reduce_50,
  1, 84, :_reduce_51,
  2, 84, :_reduce_52,
  3, 85, :_reduce_53,
  7, 61, :_reduce_54,
  1, 89, :_reduce_55,
  3, 89, :_reduce_56,
  1, 90, :_reduce_57,
  3, 90, :_reduce_58,
  0, 91, :_reduce_59,
  1, 91, :_reduce_60,
  3, 91, :_reduce_61,
  3, 91, :_reduce_62,
  5, 91, :_reduce_63,
  0, 96, :_reduce_64,
  0, 97, :_reduce_65,
  7, 91, :_reduce_66,
  3, 91, :_reduce_67,
  0, 87, :_reduce_none,
  1, 87, :_reduce_none,
  0, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 82, :_reduce_72,
  2, 82, :_reduce_73,
  3, 82, :_reduce_74,
  1, 98, :_reduce_75,
  2, 98, :_reduce_76,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  0, 100, :_reduce_79,
  0, 101, :_reduce_80,
  6, 64, :_reduce_81,
  0, 102, :_reduce_82,
  0, 103, :_reduce_83,
  5, 64, :_reduce_84,
  1, 83, :_reduce_85,
  2, 83, :_reduce_86,
  3, 83, :_reduce_87,
  1, 104, :_reduce_88,
  2, 104, :_reduce_89,
  1, 105, :_reduce_none,
  1, 86, :_reduce_91,
  1, 86, :_reduce_92,
  1, 54, :_reduce_none,
  2, 54, :_reduce_none,
  1, 106, :_reduce_none,
  2, 106, :_reduce_none,
  4, 107, :_reduce_97,
  1, 109, :_reduce_98,
  3, 109, :_reduce_99,
  2, 109, :_reduce_none,
  0, 110, :_reduce_101,
  1, 110, :_reduce_102,
  3, 110, :_reduce_103,
  4, 110, :_reduce_104,
  6, 110, :_reduce_105,
  0, 112, :_reduce_106,
  0, 113, :_reduce_107,
  7, 110, :_reduce_108,
  3, 110, :_reduce_109,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 95, :_reduce_113,
  3, 95, :_reduce_114,
  2, 95, :_reduce_115,
  4, 95, :_reduce_116,
  0, 93, :_reduce_none,
  3, 93, :_reduce_118,
  1, 108, :_reduce_none,
  0, 55, :_reduce_none,
  0, 114, :_reduce_121,
  3, 55, :_reduce_122,
  1, 62, :_reduce_none,
  0, 63, :_reduce_none,
  1, 63, :_reduce_none,
  1, 63, :_reduce_none,
  1, 63, :_reduce_none,
  1, 70, :_reduce_128,
  2, 70, :_reduce_129,
  1, 115, :_reduce_none,
  1, 115, :_reduce_none,
  1, 99, :_reduce_132,
  0, 111, :_reduce_none,
  1, 111, :_reduce_none ]

racc_reduce_n = 135

racc_shift_n = 224

racc_token_table = {
  false => 0,
  :error => 1,
  :C_DECLARATION => 2,
  :CHARACTER => 3,
  :IDENT_COLON => 4,
  :IDENTIFIER => 5,
  :INTEGER => 6,
  :STRING => 7,
  :TAG => 8,
  "%%" => 9,
  "%{" => 10,
  "%}" => 11,
  "%require" => 12,
  "%expect" => 13,
  "%define" => 14,
  "%param" => 15,
  "%lex-param" => 16,
  "%parse-param" => 17,
  "%code" => 18,
  "{" => 19,
  "}" => 20,
  "%initial-action" => 21,
  ";" => 22,
  "%union" => 23,
  "%destructor" => 24,
  "%printer" => 25,
  "%error-token" => 26,
  "%after-shift" => 27,
  "%before-reduce" => 28,
  "%after-reduce" => 29,
  "%token" => 30,
  "%type" => 31,
  "%left" => 32,
  "%right" => 33,
  "%precedence" => 34,
  "%nonassoc" => 35,
  "%rule" => 36,
  "(" => 37,
  ")" => 38,
  ":" => 39,
  "," => 40,
  "|" => 41,
  "%empty" => 42,
  "%prec" => 43,
  "?" => 44,
  "+" => 45,
  "*" => 46,
  "[" => 47,
  "]" => 48,
  "{...}" => 49 }

racc_nt_base = 50

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "C_DECLARATION",
  "CHARACTER",
  "IDENT_COLON",
  "IDENTIFIER",
  "INTEGER",
  "STRING",
  "TAG",
  "\"%%\"",
  "\"%{\"",
  "\"%}\"",
  "\"%require\"",
  "\"%expect\"",
  "\"%define\"",
  "\"%param\"",
  "\"%lex-param\"",
  "\"%parse-param\"",
  "\"%code\"",
  "\"{\"",
  "\"}\"",
  "\"%initial-action\"",
  "\";\"",
  "\"%union\"",
  "\"%destructor\"",
  "\"%printer\"",
  "\"%error-token\"",
  "\"%after-shift\"",
  "\"%before-reduce\"",
  "\"%after-reduce\"",
  "\"%token\"",
  "\"%type\"",
  "\"%left\"",
  "\"%right\"",
  "\"%precedence\"",
  "\"%nonassoc\"",
  "\"%rule\"",
  "\"(\"",
  "\")\"",
  "\":\"",
  "\",\"",
  "\"|\"",
  "\"%empty\"",
  "\"%prec\"",
  "\"?\"",
  "\"+\"",
  "\"*\"",
  "\"[\"",
  "\"]\"",
  "\"{...}\"",
  "$start",
  "input",
  "prologue_declarations",
  "bison_declarations",
  "grammar",
  "epilogue_opt",
  "prologue_declaration",
  "@1",
  "@2",
  "bison_declaration",
  "grammar_declaration",
  "rule_declaration",
  "variable",
  "value",
  "params",
  "@3",
  "@4",
  "@5",
  "@6",
  "symbol_declaration",
  "generic_symlist",
  "@7",
  "@8",
  "@9",
  "@10",
  "@11",
  "@12",
  "@13",
  "@14",
  "@15",
  "@16",
  "token_declarations",
  "symbol_declarations",
  "token_declarations_for_precedence",
  "token_declaration_list",
  "token_declaration",
  "id",
  "int_opt",
  "alias",
  "rule_args",
  "rule_rhs_list",
  "rule_rhs",
  "symbol",
  "named_ref_opt",
  "parameterizing_suffix",
  "parameterizing_args",
  "@17",
  "@18",
  "symbol_declaration_list",
  "string_as_id",
  "@19",
  "@20",
  "@21",
  "@22",
  "token_declaration_list_for_precedence",
  "token_declaration_for_precedence",
  "rules_or_grammar_declaration",
  "rules",
  "id_colon",
  "rhs_list",
  "rhs",
  "tag_opt",
  "@23",
  "@24",
  "@25",
  "generic_symlist_item" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'parser.y', 14)
  def _reduce_4(val, _values, result)
                                begin_c_declaration("%}")
                            @grammar.prologue_first_lineno = @lexer.line

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 19)
  def _reduce_5(val, _values, result)
                                end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_6(val, _values, result)
                                @grammar.prologue = val[2].s_value

    result
  end
.,.,

# reduce 7 omitted

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_8(val, _values, result)
     result = ""
    result
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_12(val, _values, result)
     @grammar.expect = val[1]
    result
  end
.,.,

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'parser.y', 37)
  def _reduce_15(val, _values, result)
                             val[1].each {|token|
                           @grammar.lex_param = Grammar::Code::NoReferenceCode.new(type: :lex_param, token_code: token).token_code.s_value
                         }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 43)
  def _reduce_16(val, _values, result)
                             val[1].each {|token|
                           @grammar.parse_param = Grammar::Code::NoReferenceCode.new(type: :parse_param, token_code: token).token_code.s_value
                         }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 49)
  def _reduce_17(val, _values, result)
                             begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 53)
  def _reduce_18(val, _values, result)
                             end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 57)
  def _reduce_19(val, _values, result)
                             @grammar.add_percent_code(id: val[1], code: val[4])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 61)
  def _reduce_20(val, _values, result)
                             begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 65)
  def _reduce_21(val, _values, result)
                             end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 69)
  def _reduce_22(val, _values, result)
                             @grammar.initial_action = Grammar::Code::InitialActionCode.new(type: :initial_action, token_code: val[3])

    result
  end
.,.,

# reduce 23 omitted

module_eval(<<'.,.,', 'parser.y', 75)
  def _reduce_24(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 79)
  def _reduce_25(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 83)
  def _reduce_26(val, _values, result)
                               @grammar.set_union(
                             Grammar::Code::NoReferenceCode.new(type: :union, token_code: val[3]),
                             val[3].line
                           )

    result
  end
.,.,

# reduce 27 omitted

module_eval(<<'.,.,', 'parser.y', 91)
  def _reduce_28(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 95)
  def _reduce_29(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

# reduce 30 omitted

module_eval(<<'.,.,', 'parser.y', 100)
  def _reduce_31(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 104)
  def _reduce_32(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 108)
  def _reduce_33(val, _values, result)
                               @grammar.add_printer(
                             ident_or_tags: val[6],
                             token_code: val[3],
                             lineno: val[3].line
                           )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 116)
  def _reduce_34(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 120)
  def _reduce_35(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 124)
  def _reduce_36(val, _values, result)
                               @grammar.add_error_token(
                             ident_or_tags: val[6],
                             token_code: val[3],
                             lineno: val[3].line
                           )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 132)
  def _reduce_37(val, _values, result)
                               begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 136)
  def _reduce_38(val, _values, result)
                               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 140)
  def _reduce_39(val, _values, result)
                               @grammar.after_shift = Grammar::Code::AfterShiftCode.new(type: :initial_action, token_code: val[3])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 144)
  def _reduce_40(val, _values, result)
                               @grammar.before_reduce = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 148)
  def _reduce_41(val, _values, result)
                               @grammar.after_reduce = val[1]

    result
  end
.,.,

# reduce 42 omitted

module_eval(<<'.,.,', 'parser.y', 154)
  def _reduce_43(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              @grammar.add_type(id: id, tag: hash[:tag])
                            }
                          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 162)
  def _reduce_44(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              sym = @grammar.add_term(id: id)
                              @grammar.add_left(sym, @precedence_number)
                            }
                          }
                          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 172)
  def _reduce_45(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              sym = @grammar.add_term(id: id)
                              @grammar.add_right(sym, @precedence_number)
                            }
                          }
                          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 182)
  def _reduce_46(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              sym = @grammar.add_term(id: id)
                              @grammar.add_precedence(sym, @precedence_number)
                            }
                          }
                          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 192)
  def _reduce_47(val, _values, result)
                              val[1].each {|hash|
                            hash[:tokens].each {|id|
                              sym = @grammar.add_term(id: id)
                              @grammar.add_nonassoc(sym, @precedence_number)
                            }
                          }
                          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 203)
  def _reduce_48(val, _values, result)
                              val[0].each {|token_declaration|
                            @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: nil, replace: true)
                          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 209)
  def _reduce_49(val, _values, result)
                              val[1].each {|token_declaration|
                            @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: val[0], replace: true)
                          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 215)
  def _reduce_50(val, _values, result)
                              val[2].each {|token_declaration|
                            @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: val[1], replace: true)
                          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 220)
  def _reduce_51(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 221)
  def _reduce_52(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 223)
  def _reduce_53(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 227)
  def _reduce_54(val, _values, result)
                            rule = Grammar::ParameterizingRule::Rule.new(val[1].s_value, val[3], val[6])
                        @grammar.add_parameterizing_rule(rule)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 231)
  def _reduce_55(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 232)
  def _reduce_56(val, _values, result)
     result = val[0].append(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 236)
  def _reduce_57(val, _values, result)
                      builder = val[0]
                  result = [builder]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 241)
  def _reduce_58(val, _values, result)
                      builder = val[2]
                  result = val[0].append(builder)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 247)
  def _reduce_59(val, _values, result)
                  reset_precs
              result = Grammar::ParameterizingRule::Rhs.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 252)
  def _reduce_60(val, _values, result)
                  reset_precs
              result = Grammar::ParameterizingRule::Rhs.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 257)
  def _reduce_61(val, _values, result)
                  token = val[1]
              token.alias_name = val[2]
              builder = val[0]
              builder.symbols << token
              result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 265)
  def _reduce_62(val, _values, result)
                    builder = val[0]
                builder.symbols << Lrama::Lexer::Token::InstantiateRule.new(s_value: val[2], location: @lexer.location, args: [val[1]])
                result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 271)
  def _reduce_63(val, _values, result)
                    builder = val[0]
                builder.symbols << Lrama::Lexer::Token::InstantiateRule.new(s_value: val[1].s_value, location: @lexer.location, args: val[3])
                result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 277)
  def _reduce_64(val, _values, result)
                  if @prec_seen
                on_action_error("multiple User_code after %prec", val[0])  if @code_after_prec
                @code_after_prec = true
              end
              begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 285)
  def _reduce_65(val, _values, result)
                  end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 289)
  def _reduce_66(val, _values, result)
                  user_code = val[3]
              user_code.alias_name = val[6]
              builder = val[0]
              builder.user_code = user_code
              result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 297)
  def _reduce_67(val, _values, result)
                  sym = @grammar.find_symbol_by_id!(val[2])
              @prec_seen = true
              builder = val[0]
              builder.precedence_sym = sym
              result = builder

    result
  end
.,.,

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

module_eval(<<'.,.,', 'parser.y', 312)
  def _reduce_72(val, _values, result)
                               result = [{tag: nil, tokens: val[0]}]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 316)
  def _reduce_73(val, _values, result)
                               result = [{tag: val[0], tokens: val[1]}]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 320)
  def _reduce_74(val, _values, result)
                             result = val[0].append({tag: val[1], tokens: val[2]})

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 323)
  def _reduce_75(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 324)
  def _reduce_76(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

# reduce 77 omitted

# reduce 78 omitted

module_eval(<<'.,.,', 'parser.y', 331)
  def _reduce_79(val, _values, result)
                  begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 335)
  def _reduce_80(val, _values, result)
                  end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 339)
  def _reduce_81(val, _values, result)
                  result = val[0].append(val[3])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 343)
  def _reduce_82(val, _values, result)
                  begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 347)
  def _reduce_83(val, _values, result)
                  end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 351)
  def _reduce_84(val, _values, result)
                  result = [val[2]]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 356)
  def _reduce_85(val, _values, result)
                                             result = [{tag: nil, tokens: val[0]}]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 360)
  def _reduce_86(val, _values, result)
                                             result = [{tag: val[0], tokens: val[1]}]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 364)
  def _reduce_87(val, _values, result)
                                             result = val[0].append({tag: val[1], tokens: val[2]})

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 367)
  def _reduce_88(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 368)
  def _reduce_89(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

# reduce 90 omitted

module_eval(<<'.,.,', 'parser.y', 372)
  def _reduce_91(val, _values, result)
     on_action_error("ident after %prec", val[0]) if @prec_seen
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 373)
  def _reduce_92(val, _values, result)
     on_action_error("char after %prec", val[0]) if @prec_seen
    result
  end
.,.,

# reduce 93 omitted

# reduce 94 omitted

# reduce 95 omitted

# reduce 96 omitted

module_eval(<<'.,.,', 'parser.y', 383)
  def _reduce_97(val, _values, result)
                 lhs = val[0]
             lhs.alias_name = val[1]
             val[3].each do |builder|
               builder.lhs = lhs
               builder.complete_input
               @grammar.add_rule_builder(builder)
             end

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 394)
  def _reduce_98(val, _values, result)
                    builder = val[0]
                if !builder.line
                  builder.line = @lexer.line - 1
                end
                result = [builder]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 402)
  def _reduce_99(val, _values, result)
                    builder = val[2]
                if !builder.line
                  builder.line = @lexer.line - 1
                end
                result = val[0].append(builder)

    result
  end
.,.,

# reduce 100 omitted

module_eval(<<'.,.,', 'parser.y', 412)
  def _reduce_101(val, _values, result)
               reset_precs
           result = Grammar::RuleBuilder.new(@rule_counter, @midrule_action_counter)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 417)
  def _reduce_102(val, _values, result)
               reset_precs
           result = Grammar::RuleBuilder.new(@rule_counter, @midrule_action_counter)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 422)
  def _reduce_103(val, _values, result)
               token = val[1]
           token.alias_name = val[2]
           builder = val[0]
           builder.add_rhs(token)
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 430)
  def _reduce_104(val, _values, result)
               token = Lrama::Lexer::Token::InstantiateRule.new(s_value: val[2], location: @lexer.location, args: [val[1]], lhs_tag: val[3])
           builder = val[0]
           builder.add_rhs(token)
           builder.line = val[1].first_line
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 438)
  def _reduce_105(val, _values, result)
               token = Lrama::Lexer::Token::InstantiateRule.new(s_value: val[1].s_value, location: @lexer.location, args: val[3], lhs_tag: val[5])
           builder = val[0]
           builder.add_rhs(token)
           builder.line = val[1].first_line
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 446)
  def _reduce_106(val, _values, result)
               if @prec_seen
             on_action_error("multiple User_code after %prec", val[0])  if @code_after_prec
             @code_after_prec = true
           end
           begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 454)
  def _reduce_107(val, _values, result)
               end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 458)
  def _reduce_108(val, _values, result)
               user_code = val[3]
           user_code.alias_name = val[6]
           builder = val[0]
           builder.user_code = user_code
           result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 466)
  def _reduce_109(val, _values, result)
               sym = @grammar.find_symbol_by_id!(val[2])
           @prec_seen = true
           builder = val[0]
           builder.precedence_sym = sym
           result = builder

    result
  end
.,.,

# reduce 110 omitted

# reduce 111 omitted

# reduce 112 omitted

module_eval(<<'.,.,', 'parser.y', 477)
  def _reduce_113(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 478)
  def _reduce_114(val, _values, result)
     result = val[0].append(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 479)
  def _reduce_115(val, _values, result)
     result = [Lrama::Lexer::Token::InstantiateRule.new(s_value: val[1].s_value, location: @lexer.location, args: val[0])]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 480)
  def _reduce_116(val, _values, result)
     result = [Lrama::Lexer::Token::InstantiateRule.new(s_value: val[0].s_value, location: @lexer.location, args: val[2])]
    result
  end
.,.,

# reduce 117 omitted

module_eval(<<'.,.,', 'parser.y', 483)
  def _reduce_118(val, _values, result)
     result = val[1].s_value
    result
  end
.,.,

# reduce 119 omitted

# reduce 120 omitted

module_eval(<<'.,.,', 'parser.y', 490)
  def _reduce_121(val, _values, result)
                        begin_c_declaration('\Z')
                    @grammar.epilogue_first_lineno = @lexer.line + 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 495)
  def _reduce_122(val, _values, result)
                        end_c_declaration
                    @grammar.epilogue = val[2].s_value

    result
  end
.,.,

# reduce 123 omitted

# reduce 124 omitted

# reduce 125 omitted

# reduce 126 omitted

# reduce 127 omitted

module_eval(<<'.,.,', 'parser.y', 506)
  def _reduce_128(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 507)
  def _reduce_129(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

# reduce 130 omitted

# reduce 131 omitted

module_eval(<<'.,.,', 'parser.y', 512)
  def _reduce_132(val, _values, result)
     result = Lrama::Lexer::Token::Ident.new(s_value: val[0])
    result
  end
.,.,

# reduce 133 omitted

# reduce 134 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Lrama
